const constants = require('./src/constants');

const REACT_FRAMEWORKS = {
  type: 'category',
  label: 'Frameworks',
  link: {
    type: 'generated-index',
    title: 'React Frameworks',
    description: "Let's learn about the most fimportant Docusaurus concepts!",
    keywords: ['hooks'],
    image: '/img/LogoFiles/logo.png',
  },
  items: ['React/Frameworks/next', 'React/Frameworks/gastby'],
};

const REACT_HOOKS = {
  type: 'category',
  label: 'Hooks',
  link: {
    type: 'generated-index',
    title: 'Docusaurus Guides',
    description: "Let's learn about the most fimportant Docusaurus concepts!",
    keywords: ['hooks'],
    image: '/img/LogoFiles/logo.png',
  },
  items: ['React/Hooks/useState', 'React/Hooks/useEffect'],
};

const REACT_GLOBAL_STATE_MANAGER = {
  type: 'category',
  label: 'Global state manager',
  link: {
    type: 'generated-index',
    title: 'Docusaurus Guides',
    description: "Let's learn about the most fimportant Docusaurus concepts!",
    keywords: ['hooks'],
    image: '/img/LogoFiles/logo.png',
  },
  items: [
    'React/Tools/Global-state-managers/redux/index',
    'React/Tools/Global-state-managers/context/index',
  ],
};
const REACT_TOOLS = {
  type: 'category',
  label: 'Tools',
  link: {
    type: 'generated-index',
    title: 'Docusaurus Guides',
    description: "Let's learn about the most fimportant Docusaurus concepts!",
    keywords: ['hooks'],
    image: '/img/LogoFiles/logo.png',
  },
  items: [
    'React/Tools/proptypes',
    'React/Tools/libs/index',
    REACT_GLOBAL_STATE_MANAGER,
  ],
};

const REACT_NATIVE = {
  type: 'category',
  label: 'React Native',
  link: {
    type: 'generated-index',
    title: 'Docusaurus Guides',
    description: "Let's learn about the most fimportant Docusaurus concepts!",
    keywords: ['hooks'],
    image: '/img/LogoFiles/logo.png',
  },
  items: ['React/React-native/react-native', 'React/React-native/libs/index'],
};

const REACT_SIDEBAR = {
  type: 'category',
  label: 'React',
  collapsed: true,
  link: {
    type: 'generated-index',
    title: 'React',
    description: 'Aqui encontraras mucho contenido sobre React',
    keywords: ['react', 'guides'],
    image: '/img/logo.svg',
  },
  items: [
    'React/Que-es-React',
    REACT_FRAMEWORKS,
    REACT_HOOKS,
    REACT_TOOLS,
    REACT_NATIVE,
  ],
};
const CSS_SIDEBAR = {
  type: 'category',
  label: 'CSS',
  link: {
    type: 'generated-index',
    title: 'Docusaurus Guides',
    description: "Let's learn about the most fimportant Docusaurus concepts!",
    keywords: ['guides'],
    image: '/img/logo.svg',
  },
  items: [
    'CSS/colecciones-assets/index',
    'CSS/Generadores-de-gradientes/index',
    'CSS/herramientas/index',
    'CSS/libs/index',
  ],
};
const JS_SIDEBAR = {
  type: 'category',
  label: 'Javascript',
  link: {
    type: 'generated-index',
    title: 'Docusaurus Guides',
    description: "Let's learn about the most fimportant Docusaurus concepts!",
    keywords: ['guides'],
    image: '/img/logo.svg',
  },
  items: [
    'Javascript/libs/index',
    {
      type: 'category',
      label: 'Frameworks',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description:
          "Let's learn about the most fimportant Docusaurus concepts!",
        keywords: ['hooks'],
        image: '/img/LogoFiles/logo.png',
      },
      items: ['Javascript/Frameworks/react'],
    },
  ],
};
const HTML_SIDEBAR = {
  type: 'category',
  label: 'HTML',
  link: {
    type: 'generated-index',
    title: 'Docusaurus Guides',
    description: "Let's learn about the most fimportant Docusaurus concepts!",
    keywords: ['guides'],
    image: '/img/logo.svg',
  },
  items: ['HTML/index'],
};

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
   */
  // But you can create a sidebar manually

  tutorialSidebar: [
    'bienvenido-doc',
    REACT_SIDEBAR,
    JS_SIDEBAR,
    CSS_SIDEBAR,
    'HTML/index',
    'interes-doc',
    {
      type: 'link',
      label: 'React Libs',
      href: constants.siteData.siteRepo,
    },
  ],
};

module.exports = sidebars;
