const constants = require('./src/constants');

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
   */
  // But you can create a sidebar manually

  tutorialSidebar: [
    'bienvenido-doc',
    {
      type: 'category',
      label: 'React',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'React',
        description: 'Aqui encontraras mucho contenido sobre React',
        keywords: ['react', 'guides'],
        image: '/img/logo.svg',
      },
      items: [
        'React/Frameworks/next',
        'React/Hooks/useState',
        'React/Hooks/useEffect',
        {
          type: 'category',
          label: 'Frameworks',
          link: {
            type: 'generated-index',
            title: 'React Frameworks',
            description:
              "Let's learn about the most fimportant Docusaurus concepts!",
            keywords: ['hooks'],
            image: '/img/LogoFiles/logo.png',
          },
          items: ['React/Frameworks/next', 'React/Frameworks/gastby'],
        },
        {
          type: 'category',
          label: 'Hooks',
          link: {
            type: 'generated-index',
            title: 'Docusaurus Guides',
            description:
              "Let's learn about the most fimportant Docusaurus concepts!",
            keywords: ['hooks'],
            image: '/img/LogoFiles/logo.png',
          },
          items: ['React/Hooks/useState', 'React/Hooks/useEffect'],
        },
        {
          type: 'category',
          label: 'Tools',
          link: {
            type: 'generated-index',
            title: 'Docusaurus Guides',
            description:
              "Let's learn about the most fimportant Docusaurus concepts!",
            keywords: ['hooks'],
            image: '/img/LogoFiles/logo.png',
          },
          items: ['React/Tools/proptypes'],
        },
        {
          type: 'category',
          label: 'Libs',
          link: {
            type: 'generated-index',
            title: 'Docusaurus Guides',
            description:
              "Let's learn about the most fimportant Docusaurus concepts!",
            keywords: ['hooks'],
            image: '/img/LogoFiles/logo.png',
          },
          items: [
            'React/Frameworks/next',
            'React/Hooks/useState',
            'React/Hooks/useEffect',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'HTML',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description:
          "Let's learn about the most fimportant Docusaurus concepts!",
        keywords: ['guides'],
        image: '/img/logo.svg',
      },
      items: [
        'React/Frameworks/next',
        'React/Hooks/useState',
        'React/Hooks/useEffect',
      ],
    },
    {
      type: 'category',
      label: 'Javascript',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description:
          "Let's learn about the most fimportant Docusaurus concepts!",
        keywords: ['guides'],
        image: '/img/logo.svg',
      },
      items: [
        'React/Frameworks/next',
        'React/Hooks/useState',
        'React/Hooks/useEffect',
      ],
    },
    {
      type: 'category',
      label: 'CSS',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description:
          "Let's learn about the most fimportant Docusaurus concepts!",
        keywords: ['guides'],
        image: '/img/logo.svg',
      },
      items: [
        'React/Frameworks/next',
        'React/Hooks/useState',
        'React/Hooks/useEffect',
        'CSS/Generadores-de-gradientes/index',
      ],
    },
    'interes-doc',
    {
      type: 'link',
      label: 'React Libs',
      href: constants.siteData.siteRepo,
    },
  ],
};

module.exports = sidebars;
